on: [pull_request]
jobs:
  job_1:
    name: Check PR to see if reviewers should be notified
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm install
      - name: create env file
        run: |
          touch .env
          echo SOURCEGRAPH_API_TOKEN =${{ secrets.ENGINE_API_KEY }}; SLACK_TOKEN= ${{ secrets.SLACKTOKEN }}>> .env
      - name: Build and deploy Segment Function
        uses: christyharagan/sourcegraph-search-action@v0.1.7
        with: # Set the secret as an input
          sourcegraph_domain_name: demo.sourcegraph.com
          sourcegraph_org_name: acme-corp
